@extends('layouts.app')

@section('title', 'Text to Speech Online Free - Urdu and English Voices | Azlaan Tools')
@section('meta_description', 'Free Text to Speech tool: type text and hear it spoken aloud with Urdu and English voices, adjustable speed and pitch. No signup, works in your browser.')

@section('content')
<div class="container py-4">
    <h1 class="mb-3">Text to Speech</h1>
    <p class="lead">Turn written text into natural spoken audio - free and instant. Choose a voice (Urdu and English supported), adjust speed and pitch, and listen.</p>

    <div id="alertBox" class="alert alert-danger d-none" role="alert"></div>
    <div id="successBox" class="alert alert-success d-none" role="alert"></div>
    <div id="noVoiceBox" class="alert alert-warning d-none" role="alert">No speech voices were found in this browser yet. Voices may load after a moment, or try Chrome / Edge on desktop or Android for the widest voice selection including Urdu.</div>

    <div class="card shadow-sm mb-4">
        <div class="card-body">
            <label for="ttsInput" class="form-label fw-semibold">Text to Speak</label>
            <textarea id="ttsInput" class="form-control" rows="7" placeholder="Type or paste text here, for example: Assalam-o-Alaikum, welcome to Azlaan Tools..."></textarea>
            <div class="small text-muted mt-2">Characters: <strong id="charCount">0</strong> &nbsp; Words: <strong id="wordCount">0</strong></div>

            <div class="row g-3 mt-2">
                <div class="col-md-12">
                    <label for="voiceSelect" class="form-label fw-semibold">Voice</label>
                    <select id="voiceSelect" class="form-select">
                        <option value="">Default voice (loading...)</option>
                    </select>
                    <div class="form-text">Urdu voices (ur-PK) are listed first when available, followed by English voices.</div>
                </div>
                <div class="col-md-6">
                    <label for="rateRange" class="form-label fw-semibold">Speed (Rate): <span id="rateVal">1.0</span></label>
                    <input type="range" id="rateRange" class="form-range" min="0.5" max="2" step="0.1" value="1">
                </div>
                <div class="col-md-6">
                    <label for="pitchRange" class="form-label fw-semibold">Pitch: <span id="pitchVal">1.0</span></label>
                    <input type="range" id="pitchRange" class="form-range" min="0" max="2" step="0.1" value="1">
                </div>
            </div>

            <div class="d-flex flex-wrap gap-2 mt-3">
                <button type="button" id="speakBtn" class="btn btn-success">Speak</button>
                <button type="button" id="pauseBtn" class="btn btn-warning">Pause</button>
                <button type="button" id="resumeBtn" class="btn btn-primary">Resume</button>
                <button type="button" id="stopBtn" class="btn btn-outline-danger">Stop</button>
            </div>
            <p class="small text-muted mt-3 mb-0" id="statusText">Ready.</p>
        </div>
    </div>

    <div class="alert alert-info">
        <strong>Privacy note:</strong> Speech is generated by your own browser on your device - your text is not sent to our server.
    </div>

    <h2>How to use</h2>
    <ol>
        <li>Type or paste the text you want to hear in the box above.</li>
        <li>Pick a voice from the dropdown - Urdu voices appear first when your device provides them.</li>
        <li>Adjust the speed and pitch sliders to your liking.</li>
        <li>Click <strong>Speak</strong> to listen, and use <strong>Pause</strong>, <strong>Resume</strong> or <strong>Stop</strong> to control playback.</li>
    </ol>
</div>
@endsection

@section('scripts')
<script>
(function () {
    var input = document.getElementById('ttsInput');
    var voiceSelect = document.getElementById('voiceSelect');
    var rateRange = document.getElementById('rateRange');
    var pitchRange = document.getElementById('pitchRange');
    var rateVal = document.getElementById('rateVal');
    var pitchVal = document.getElementById('pitchVal');
    var alertBox = document.getElementById('alertBox');
    var successBox = document.getElementById('successBox');
    var noVoiceBox = document.getElementById('noVoiceBox');
    var statusText = document.getElementById('statusText');
    var voices = [];

    function showError(msg) {
        alertBox.textContent = msg;
        alertBox.classList.remove('d-none');
        successBox.classList.add('d-none');
    }
    function showSuccess(msg) {
        successBox.textContent = msg;
        successBox.classList.remove('d-none');
        alertBox.classList.add('d-none');
    }
    function hideAlerts() {
        alertBox.classList.add('d-none');
        successBox.classList.add('d-none');
    }
    function updateCounts() {
        var t = input.value;
        document.getElementById('charCount').textContent = t.length;
        document.getElementById('wordCount').textContent = t.trim() ? t.trim().split(/\s+/).length : 0;
    }
    function voiceRank(v) {
        var lang = (v.lang || '').toLowerCase().replace('_', '-');
        if (lang.indexOf('ur') === 0) return 0;
        if (lang.indexOf('en') === 0) return 1;
        return 2;
    }
    function populateVoices() {
        if (!('speechSynthesis' in window)) return;
        var all = window.speechSynthesis.getVoices();
        if (!all || all.length === 0) {
            noVoiceBox.classList.remove('d-none');
            return;
        }
        voices = all.slice().sort(function (a, b) {
            var ra = voiceRank(a);
            var rb = voiceRank(b);
            if (ra !== rb) return ra - rb;
            return (a.name || '').localeCompare(b.name || '');
        } );
        noVoiceBox.classList.add('d-none');
        var current = voiceSelect.value;
        voiceSelect.innerHTML = '';
        voices.forEach(function (v, idx) {
            var opt = document.createElement('option');
            opt.value = String(idx);
            var label = v.name + ' (' + v.lang + ')';
            if (v.default) label += ' - Default';
            opt.textContent = label;
            voiceSelect.appendChild(opt);
        } );
        if (current !== '' && voices[parseInt(current, 10)]) {
            voiceSelect.value = current;
        }
    }

    if (!('speechSynthesis' in window)) {
        showError('Text to Speech is not supported in this browser. Please try Chrome, Edge or Safari.');
        document.getElementById('speakBtn').disabled = true;
    } else {
        populateVoices();
        if (typeof window.speechSynthesis.onvoiceschanged !== 'undefined') {
            window.speechSynthesis.onvoiceschanged = populateVoices;
        }
        setTimeout(populateVoices, 500);
        setTimeout(populateVoices, 1500);
    }

    input.addEventListener('input', updateCounts);
    rateRange.addEventListener('input', function () {
        rateVal.textContent = Number(rateRange.value).toFixed(1);
    } );
    pitchRange.addEventListener('input', function () {
        pitchVal.textContent = Number(pitchRange.value).toFixed(1);
    } );

    document.getElementById('speakBtn').addEventListener('click', function () {
        hideAlerts();
        if (!('speechSynthesis' in window)) {
            showError('Text to Speech is not supported in this browser.');
            return;
        }
        var text = input.value.trim();
        if (!text) {
            showError('Please type some text first.');
            return;
        }
        window.speechSynthesis.cancel();
        var utter = new SpeechSynthesisUtterance(text);
        var idx = voiceSelect.value === '' ? -1 : parseInt(voiceSelect.value, 10);
        if (idx >= 0 && voices[idx]) {
            utter.voice = voices[idx];
            utter.lang = voices[idx].lang;
        }
        utter.rate = Number(rateRange.value);
        utter.pitch = Number(pitchRange.value);
        utter.onstart = function () {
            statusText.textContent = 'Speaking...';
        };
        utter.onend = function () {
            statusText.textContent = 'Finished.';
        };
        utter.onerror = function (e) {
            if (e && e.error && e.error !== 'canceled' && e.error !== 'interrupted') {
                statusText.textContent = 'Ready.';
                showError('Speech failed: ' + e.error + '. Please try another voice.');
            }
        };
        window.speechSynthesis.speak(utter);
        statusText.textContent = 'Speaking...';
    } );

    document.getElementById('pauseBtn').addEventListener('click', function () {
        if ('speechSynthesis' in window && window.speechSynthesis.speaking) {
            window.speechSynthesis.pause();
            statusText.textContent = 'Paused.';
        }
    } );

    document.getElementById('resumeBtn').addEventListener('click', function () {
        if ('speechSynthesis' in window && window.speechSynthesis.paused) {
            window.speechSynthesis.resume();
            statusText.textContent = 'Speaking...';
        }
    } );

    document.getElementById('stopBtn').addEventListener('click', function () {
        if ('speechSynthesis' in window) {
            window.speechSynthesis.cancel();
            statusText.textContent = 'Stopped.';
        }
    } );

    updateCounts();
} )();
</script>
@endsection
